### ISSUE TITLE
Mistake?

### ISSUE THREAD

**Issue by TeaOwO** [CHNJohnHK/Material-You-App-Repository#1]
Discord does not have monet.![Screenshot_20230921-173449~2.png](https://github.com/CHNJohnHK/Material-You-App-Repository/assets/123305689/9550d92c-2ce0-481a-b99f-284e07eef3d8)

**Comment by huoyan1231** [comment]
its alpha version

**Comment by TeaOwO** [comment]
Yes I know, I have the alpha version and it doesn't have monet

**Comment by huoyan1231** [comment]
oh its a mistake

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TeaOwO** [comment]
Will close when fixed :)

**Comment by CHNJohnHK** [comment]
fixed

https://github.com/CHNJohnHK/Material-You-App-Repository/commit/6199dc69b73dc9fc9a4fa224383630eff0639c5e
https://github.com/CHNJohnHK/Material-You-App-Repository/commit/7140bfdde8a277fa64e8d5b3cfbb4be2af55cdd3
